diracx:
  hostname: <your_hostname>
  service:
    port: 8000
  settings:
    DIRACX_SERVICE_AUTH_ALLOWED_REDIRECTS: '["https://<your_hostname>:8000/api/docs/oauth2-redirect","https://<your_hostname>:8000/#authentication-callback"]'
    DIRACX_SANDBOX_STORE_BUCKET_NAME: demo-sandboxes
    DIRACX_SANDBOX_STORE_S3_CLIENT_KWARGS: '{"endpoint_url": "http://diracx-minio:9000", "aws_access_key_id": "console", "aws_secret_access_key": "console123"}'
    DIRACX_SANDBOX_STORE_AUTO_CREATE_BUCKET: "true"
  sqlDbs:
    dbs:
      AuthDB:
      JobDB:
      JobLoggingDB:
      SandboxMetadataDB:
      TaskQueueDB:
  osDbs:
    dbs:
      JobParametersDB:

ingress:
  enabled: true
  className: "traefik"
  tlsSecretName: myingress-cert
  annotations: {}
    
developer:
  enabled: false

